# Generated by Django 6.0.7 on 2026-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('resource', 'day_of_week', 'start_time', 'end_time'), name='unique_resource_availability'),
        ),
    ]
