# Generated by Django 6.0.7 on 2026-08-15 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringbooking',
            options={'verbose_name': 'Reserva recurrente', 'verbose_name_plural': 'Reservas recurrentes'},
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_bookings', to='bookings.recurringbooking'),
        ),
        migrations.AddField(
            model_name='recurringbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recurringbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recurringbooking',
            constraint=models.UniqueConstraint(fields=('resource', 'user', 'day_of_week', 'start_time', 'end_time', 'start_date', 'end_date'), name='unique_recurring_booking'),
        ),
    ]
