# Generated by Django 6.0.7 on 2026-08-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_recurringbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='court_type',
            field=models.CharField(choices=[('indoor', 'Cubierta'), ('outdoor', 'Exterior')], default='outdoor', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
