# Generated by Django 6.0.7 on 2026-08-15 16:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def backfill_monthly_day_of_month(apps, schema_editor):
    RecurringBooking = apps.get_model("bookings", "RecurringBooking")
    for booking in RecurringBooking.objects.filter(
        frequency="monthly", day_of_month__isnull=True
    ).iterator():
        booking.day_of_month = booking.start_date.day
        # Legacy rows carry day_of_week NOT NULL (old schema). The new
        # CheckConstraint requires day_of_week IS NULL for monthly rows, so
        # null it here or the constraint addition crashes with IntegrityError.
        booking.day_of_week = None
        booking.save(update_fields=["day_of_month", "day_of_week"])


def reverse_backfill_monthly_day_of_month(apps, schema_editor):
    # The forward guard nulls day_of_week on monthly rows, so the reverse must
    # restore it: the 0005 AlterField back to NOT NULL fails on NULL rows.
    RecurringBooking = apps.get_model("bookings", "RecurringBooking")
    for booking in RecurringBooking.objects.filter(
        frequency="monthly", day_of_week__isnull=True
    ).iterator():
        booking.day_of_week = booking.start_date.weekday()
        booking.save(update_fields=["day_of_week"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_recurringbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbooking',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='recurringbooking',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.RunPython(
            backfill_monthly_day_of_month,
            reverse_backfill_monthly_day_of_month,
        ),
        migrations.RemoveConstraint(
            model_name='recurringbooking',
            name='unique_recurring_booking',
        ),
        migrations.AddConstraint(
            model_name='recurringbooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_of_month__isnull', True), ('day_of_week__isnull', False), ('frequency', 'weekly')), models.Q(('day_of_month__isnull', False), ('day_of_week__isnull', True), ('frequency', 'monthly')), _connector='OR'), name='check_recurring_frequency_day'),
        ),
        migrations.AddConstraint(
            model_name='recurringbooking',
            constraint=models.UniqueConstraint(fields=('resource', 'user', 'frequency', 'day_of_week', 'day_of_month', 'start_time', 'end_time', 'start_date', 'end_date'), name='unique_recurring_booking'),
        ),
        migrations.AddConstraint(
            model_name='recurringbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'weekly')), fields=('resource', 'user', 'day_of_week', 'start_time', 'end_time', 'start_date', 'end_date'), name='unique_weekly_recurring'),
        ),
        migrations.AddConstraint(
            model_name='recurringbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency', 'monthly')), fields=('resource', 'user', 'day_of_month', 'start_time', 'end_time', 'start_date', 'end_date'), name='unique_monthly_recurring'),
        ),
    ]
